// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	repoPoolFieldNames          = builder.RawFieldNames(&RepoPool{})
	repoPoolRows                = strings.Join(repoPoolFieldNames, ",")
	repoPoolRowsExpectAutoSet   = strings.Join(stringx.Remove(repoPoolFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	repoPoolRowsWithPlaceHolder = strings.Join(stringx.Remove(repoPoolFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	repoPoolModel interface {
		Insert(ctx context.Context, data *RepoPool) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RepoPool, error)
		Update(ctx context.Context, data *RepoPool) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRepoPoolModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RepoPool struct {
		Id        uint64       `db:"id"`         // id 无符号自增
		Identity  string       `db:"identity"`   // 唯一标识
		Hash      string       `db:"hash"`       // 哈希值
		Name      string       `db:"name"`       // 名称
		Ext       string       `db:"ext"`        // 扩展名
		Size      int64      `db:"size"`       // 文件大小
		Path      string       `db:"path"`       // 文件路径
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间
	}
)

func newRepoPoolModel(conn sqlx.SqlConn) *defaultRepoPoolModel {
	return &defaultRepoPoolModel{
		conn:  conn,
		table: "`repo_pool`",
	}
}

func (m *defaultRepoPoolModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRepoPoolModel) FindOne(ctx context.Context, id uint64) (*RepoPool, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", repoPoolRows, m.table)
	var resp RepoPool
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRepoPoolModel) Insert(ctx context.Context, data *RepoPool) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, repoPoolRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Identity, data.Hash, data.Name, data.Ext, data.Size, data.Path, data.DeletedAt)
	return ret, err
}

func (m *defaultRepoPoolModel) Update(ctx context.Context, data *RepoPool) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, repoPoolRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Identity, data.Hash, data.Name, data.Ext, data.Size, data.Path, data.DeletedAt, data.Id)
	return err
}

func (m *defaultRepoPoolModel) tableName() string {
	return m.table
}
