// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRepoFieldNames          = builder.RawFieldNames(&UserRepo{})
	userRepoRows                = strings.Join(userRepoFieldNames, ",")
	userRepoRowsExpectAutoSet   = strings.Join(stringx.Remove(userRepoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRepoRowsWithPlaceHolder = strings.Join(stringx.Remove(userRepoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userRepoModel interface {
		Insert(ctx context.Context, data *UserRepo) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserRepo, error)
		Update(ctx context.Context, data *UserRepo) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserRepoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserRepo struct {
		Id           uint64         `db:"id"`            // id 无符号自增
		Identity     string         `db:"identity"`      // 唯一标识
		UserIdentity string         `db:"user_identity"` // 用户标识
		RepoIdentity string         `db:"repo_identity"` // 仓库标识
		ParentId     sql.NullInt64  `db:"parent_id"`     // 父级标识
		Ext          sql.NullString `db:"ext"`           // 扩展名
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
		DeletedAt    sql.NullTime   `db:"deleted_at"`    // 删除时间
	}
)

func newUserRepoModel(conn sqlx.SqlConn) *defaultUserRepoModel {
	return &defaultUserRepoModel{
		conn:  conn,
		table: "`user_repo`",
	}
}

func (m *defaultUserRepoModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserRepoModel) FindOne(ctx context.Context, id uint64) (*UserRepo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRepoRows, m.table)
	var resp UserRepo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRepoModel) Insert(ctx context.Context, data *UserRepo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userRepoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepoIdentity, data.ParentId, data.Ext, data.DeletedAt)
	return ret, err
}

func (m *defaultUserRepoModel) Update(ctx context.Context, data *UserRepo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRepoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepoIdentity, data.ParentId, data.Ext, data.DeletedAt, data.Id)
	return err
}

func (m *defaultUserRepoModel) tableName() string {
	return m.table
}
