// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userShareFieldNames          = builder.RawFieldNames(&UserShare{})
	userShareRows                = strings.Join(userShareFieldNames, ",")
	userShareRowsExpectAutoSet   = strings.Join(stringx.Remove(userShareFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userShareRowsWithPlaceHolder = strings.Join(stringx.Remove(userShareFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userShareModel interface {
		Insert(ctx context.Context, data *UserShare) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserShare, error)
		Update(ctx context.Context, data *UserShare) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserShareModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserShare struct {
		Id           uint64        `db:"id"`            // id 无符号自增
		Identity     string        `db:"identity"`      // 唯一标识
		UserIdentity string        `db:"user_identity"` // 用户标识
		RepoIdentity string        `db:"repo_identity"` // 仓库标识
		ExpireTime   sql.NullInt64 `db:"expire_time"`   // 过期时间
		CreatedAt    time.Time     `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time     `db:"updated_at"`    // 更新时间
	}
)

func newUserShareModel(conn sqlx.SqlConn) *defaultUserShareModel {
	return &defaultUserShareModel{
		conn:  conn,
		table: "`user_share`",
	}
}

func (m *defaultUserShareModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserShareModel) FindOne(ctx context.Context, id uint64) (*UserShare, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userShareRows, m.table)
	var resp UserShare
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserShareModel) Insert(ctx context.Context, data *UserShare) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userShareRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepoIdentity, data.ExpireTime)
	return ret, err
}

func (m *defaultUserShareModel) Update(ctx context.Context, data *UserShare) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userShareRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepoIdentity, data.ExpireTime, data.Id)
	return err
}

func (m *defaultUserShareModel) tableName() string {
	return m.table
}
