// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type DataResponse[T any] struct {
	BaseResponse
	Data T `json:"data"`
}

type FileItem struct {
	Identity  string `json:"identity"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	Size      int64  `json:"size"`
	Path      string `json:"path"`
	CreatedAt string `json:"created_at"`
}

type FileListReq struct {
	ParentId *int64 `form:"parent_id,omitempty"`
	Page     *int   `form:"page,omitempty"`
	Size     *int   `form:"size,omitempty"`
}

type FileMoveReq struct {
	Identity string `json:"identity"`
	ParentId int64  `json:"parent_id"` // 正常情况下不应该是可选
}

type FileRenameReq struct {
	Identity string `json:"identity"`
	NewName  string `json:"new_name"`
}

type FileUploadReq struct {
	File     string `form:"file"`
	ParentId *int64 `form:"parent_id,omitempty"`
}

type FolderCreateReq struct {
	Name     string `json:"name"`
	ParentId *int64 `form:"parent_id,omitempty"`
}

type IdFormReq struct {
	Identity string `form:"identity"`
}

type IdJsonReq struct {
	Identity string `json:"identity"`
}

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	UserBasicInfo
}

type PageResponse[T any] struct {
	BaseResponse
	Data  []T   `json:"data"`
	Total int64 `json:"total"`
}

type PopShareReq struct {
	Limit *int `form:"limit,default=10"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type ShareBasicInfo struct {
	Identity     string `json:"identity"`
	UserIdentity string `json:"user_identity"`
	RepoIdentity string `json:"repo_identity"`
	ExpireTime   int64  `json:"expire_time"` // Unix时间戳
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type ShareCreateReq struct {
	RepoIdentity string  `json:"repo_identity"`
	ExpireTime   *int64  `json:"expire_time,omitempty"` // 秒数，0表示永久
	Password     *string `json:"password,omitempty"`    // 可选密码
}

type ShareDetailInfo struct {
	ShareBasicInfo
	FileName    string `json:"file_name"`
	FileSize    int64  `json:"file_size"`
	FileExt     string `json:"file_ext"`
	DownloadNum int64  `json:"download_num"` // 下载次数
}

type ShareListItem struct {
	ShareBasicInfo
	FileName  string `json:"file_name"`
	FileExt   string `json:"file_ext"`
	IsExpired bool   `json:"is_expired"`
}

type ShareStats struct {
	TotalShares    int64 `json:"total_shares"`
	ActiveShares   int64 `json:"active_shares"`
	TotalDownloads int64 `json:"total_downloads"`
}

type ShareVerifyReq struct {
	Identity string  `json:"identity"`
	Password *string `json:"password,omitempty"` // 如果有密码保护
}

type ShareVerifyResp struct {
	Valid        bool   `json:"valid"`
	FileName     string `json:"file_name"`
	FileSize     int64  `json:"file_size"`
	FileExt      string `json:"file_ext"`
	ExpireTime   int64  `json:"expire_time"`
	NeedPassword bool   `json:"need_password"`
}

// type T struct {
// 	Data interface{}
// }

type UserBasicInfo struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	Email    string `json:"email"`
}

type UserDetailResp struct {
	UserBasicInfo
	CreatedAt string `json:"created_at"`
}

type UserRepoCreateReq struct {
	RepoIdentity string  `json:"repo_identity"`
	ParentId     *int64  `form:"parent_id,omitempty"`
	Ext          *string `json:"ext,omitempty"`
}

type UserRepoDetail struct {
	UserRepoItem
	Name string `json:"name"`
	Size int64  `json:"size"`
	Path string `json:"path"`
}

type UserRepoItem struct {
	Identity     string `json:"identity"`
	UserIdentity string `json:"user_identity"`
	RepoIdentity string `json:"repo_identity"`
	ParentId     int64  `json:"parent_id"`
	Ext          string `json:"ext"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type UserRepoListReq struct {
	ParentId *int64 `form:"parent_id,omitempty"`
	Page     *int   `form:"page,omitempty"`
	Size     *int   `form:"size,omitempty"`
}

type UserRepoMoveReq struct {
	Identity string `json:"identity"`
	ParentId int64  `json:"parent_id"` // 正常情况下不应该是可选
}
