-- 创建数据库
CREATE DATABASE cloud_disk
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

-- 切换到创建的数据库
USE cloud_disk;

-- 创建 user 表
CREATE TABLE user (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'id 无符号自增',
  PRIMARY KEY (id),
  identity VARCHAR(36) NOT NULL COMMENT '用户唯一标识',
  name VARCHAR(60) NOT NULL COMMENT '用户姓名',
  password VARCHAR(32) NOT NULL COMMENT '用户密码',
  email VARCHAR(100) NOT NULL COMMENT '用户邮箱',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间'
);

-- 创建 repo_pool 表
CREATE TABLE repo_pool (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'id 无符号自增',
  PRIMARY KEY (id),
  identity VARCHAR(36) NOT NULL COMMENT '唯一标识',
  hash VARCHAR(36) NOT NULL COMMENT '哈希值',
  name VARCHAR(255) NOT NULL COMMENT '名称',
  ext VARCHAR(255) NOT NULL COMMENT '扩展名',
  size DOUBLE NOT NULL COMMENT '文件大小',
  path VARCHAR(255) NOT NULL COMMENT '文件路径',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间'
);

-- 创建 user_repo 表
CREATE TABLE user_repo (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'id 无符号自增',
  PRIMARY KEY (id),
  identity VARCHAR(36) NOT NULL COMMENT '唯一标识',
  user_identity VARCHAR(36) NOT NULL COMMENT '用户标识',
  repo_identity VARCHAR(36) NOT NULL COMMENT '仓库标识',
  parent_id INT(11) COMMENT '父级标识',
  ext VARCHAR(255) COMMENT '扩展名',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间'
);

-- 创建 user_share 表
CREATE TABLE user_share (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'id 无符号自增',
  PRIMARY KEY (id),
  identity VARCHAR(36) NOT NULL COMMENT '唯一标识',
  user_identity VARCHAR(36) NOT NULL COMMENT '用户标识',
  repo_identity VARCHAR(36) NOT NULL COMMENT '仓库标识',
  expire_time INT(11) COMMENT '过期时间',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);
